import { DevicePreset } from '../../../shared/types';

export const DEVICE_PRESETS: DevicePreset[] = [
  // iPhone
  { name: 'iPhone 16 Pro Max', width: 440, height: 956, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 16 Pro', width: 402, height: 874, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 16 Plus', width: 430, height: 932, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 16', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 15 Pro Max', width: 430, height: 932, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 15 Pro', width: 393, height: 852, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 15 Plus', width: 430, height: 932, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 15', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 14 Pro Max', width: 430, height: 932, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 14 Pro', width: 393, height: 852, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 14 Plus', width: 428, height: 926, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 14', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 13 Pro Max', width: 428, height: 926, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 13 Pro', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 13', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 13 Mini', width: 375, height: 812, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 12 Pro Max', width: 428, height: 926, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 12 Pro', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 12', width: 390, height: 844, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone 12 Mini', width: 375, height: 812, deviceScaleFactor: 3, category: 'iPhone' },
  { name: 'iPhone SE (3rd gen)', width: 375, height: 667, deviceScaleFactor: 2, category: 'iPhone' },
  { name: 'iPhone SE (2nd gen)', width: 375, height: 667, deviceScaleFactor: 2, category: 'iPhone' },
  // iPad
  { name: 'iPad Pro 13" (M4)', width: 1024, height: 1366, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad Pro 11" (M4)', width: 834, height: 1194, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad Air 13"', width: 1024, height: 1366, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad Air 11"', width: 820, height: 1180, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad Mini (7th gen)', width: 768, height: 1024, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad (10th gen)', width: 810, height: 1080, deviceScaleFactor: 2, category: 'iPad' },
  { name: 'iPad (9th gen)', width: 768, height: 1024, deviceScaleFactor: 2, category: 'iPad' },
  // Samsung Galaxy S
  { name: 'Galaxy S25 Ultra', width: 384, height: 824, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S25+', width: 375, height: 812, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S25', width: 360, height: 780, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S24 Ultra', width: 384, height: 824, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S24+', width: 375, height: 812, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S24', width: 360, height: 780, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S23 Ultra', width: 384, height: 824, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S23+', width: 375, height: 812, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S23', width: 360, height: 780, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S22 Ultra', width: 384, height: 824, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S22+', width: 375, height: 812, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  { name: 'Galaxy S22', width: 360, height: 780, deviceScaleFactor: 3, category: 'Samsung Galaxy S' },
  // Samsung Galaxy A
  { name: 'Galaxy A55', width: 360, height: 800, deviceScaleFactor: 3, category: 'Samsung Galaxy A' },
  { name: 'Galaxy A54', width: 360, height: 800, deviceScaleFactor: 3, category: 'Samsung Galaxy A' },
  { name: 'Galaxy A35', width: 360, height: 800, deviceScaleFactor: 3, category: 'Samsung Galaxy A' },
  { name: 'Galaxy A25', width: 360, height: 800, deviceScaleFactor: 3, category: 'Samsung Galaxy A' },
  { name: 'Galaxy A15', width: 360, height: 800, deviceScaleFactor: 3, category: 'Samsung Galaxy A' },
  { name: 'Galaxy A05', width: 360, height: 780, deviceScaleFactor: 2, category: 'Samsung Galaxy A' },
  // Samsung Galaxy Z
  { name: 'Z Fold 6 (unfolded)', width: 848, height: 1080, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Fold 6 (folded)', width: 390, height: 844, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Flip 6 (open)', width: 360, height: 748, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Flip 6 (closed)', width: 260, height: 512, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Fold 5 (unfolded)', width: 848, height: 1080, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Fold 5 (folded)', width: 390, height: 844, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Flip 5 (open)', width: 360, height: 748, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  { name: 'Z Flip 5 (closed)', width: 260, height: 512, deviceScaleFactor: 3, category: 'Samsung Galaxy Z' },
  // Google Pixel
  { name: 'Pixel 9 Pro XL', width: 412, height: 892, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 9 Pro', width: 393, height: 852, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 9', width: 393, height: 852, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 8 Pro', width: 412, height: 892, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 8', width: 393, height: 852, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 8a', width: 393, height: 852, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 7 Pro', width: 412, height: 892, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 7', width: 393, height: 851, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 7a', width: 393, height: 851, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 6 Pro', width: 412, height: 892, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 6', width: 393, height: 851, deviceScaleFactor: 3, category: 'Google Pixel' },
  { name: 'Pixel 6a', width: 393, height: 851, deviceScaleFactor: 3, category: 'Google Pixel' },
  // OnePlus
  { name: 'OnePlus 13', width: 393, height: 851, deviceScaleFactor: 3, category: 'OnePlus' },
  { name: 'OnePlus 12', width: 393, height: 851, deviceScaleFactor: 3, category: 'OnePlus' },
  { name: 'OnePlus 12R', width: 393, height: 851, deviceScaleFactor: 3, category: 'OnePlus' },
  { name: 'OnePlus Nord 4', width: 360, height: 800, deviceScaleFactor: 3, category: 'OnePlus' },
  { name: 'OnePlus Nord CE4', width: 360, height: 800, deviceScaleFactor: 3, category: 'OnePlus' },
  { name: 'OnePlus Nord CE3', width: 360, height: 800, deviceScaleFactor: 3, category: 'OnePlus' },
  // Xiaomi
  { name: 'Xiaomi 14 Ultra', width: 393, height: 874, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Xiaomi 14 Pro', width: 393, height: 874, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Xiaomi 14', width: 393, height: 874, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Xiaomi 14T Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Xiaomi 14T', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Redmi Note 13 Pro+', width: 393, height: 873, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Redmi Note 13 Pro', width: 393, height: 873, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Redmi Note 13', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'Redmi 13C', width: 360, height: 800, deviceScaleFactor: 2, category: 'Xiaomi' },
  { name: 'POCO X6 Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'POCO X6', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  { name: 'POCO M6 Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'Xiaomi' },
  // Motorola
  { name: 'Edge 50 Ultra', width: 393, height: 874, deviceScaleFactor: 3, category: 'Motorola' },
  { name: 'Edge 50 Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'Motorola' },
  { name: 'Edge 50', width: 393, height: 851, deviceScaleFactor: 3, category: 'Motorola' },
  { name: 'Moto G Power (2024)', width: 360, height: 800, deviceScaleFactor: 2, category: 'Motorola' },
  { name: 'Moto G84', width: 360, height: 800, deviceScaleFactor: 2, category: 'Motorola' },
  { name: 'Moto G54', width: 360, height: 800, deviceScaleFactor: 2, category: 'Motorola' },
  { name: 'Razr 50 Ultra (open)', width: 360, height: 748, deviceScaleFactor: 3, category: 'Motorola' },
  { name: 'Razr 50 (open)', width: 360, height: 748, deviceScaleFactor: 3, category: 'Motorola' },
  // OPPO
  { name: 'Find X8 Pro', width: 393, height: 874, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'Find X8', width: 393, height: 874, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'Find X7 Ultra', width: 393, height: 874, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'Reno 12 Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'Reno 12', width: 393, height: 851, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'Reno 11', width: 393, height: 851, deviceScaleFactor: 3, category: 'OPPO' },
  { name: 'A98', width: 360, height: 800, deviceScaleFactor: 2, category: 'OPPO' },
  // Realme
  { name: 'GT 6 Pro', width: 393, height: 874, deviceScaleFactor: 3, category: 'Realme' },
  { name: 'GT 6', width: 393, height: 851, deviceScaleFactor: 3, category: 'Realme' },
  { name: '13 Pro+', width: 393, height: 873, deviceScaleFactor: 3, category: 'Realme' },
  { name: '13 Pro', width: 393, height: 851, deviceScaleFactor: 3, category: 'Realme' },
  { name: '13', width: 393, height: 851, deviceScaleFactor: 3, category: 'Realme' },
  { name: 'C67', width: 360, height: 800, deviceScaleFactor: 2, category: 'Realme' },
  { name: 'C55', width: 360, height: 800, deviceScaleFactor: 2, category: 'Realme' },
  // Sony
  { name: 'Xperia 1 VI', width: 384, height: 824, deviceScaleFactor: 3, category: 'Sony' },
  { name: 'Xperia 1 V', width: 384, height: 824, deviceScaleFactor: 3, category: 'Sony' },
  { name: 'Xperia 5 VI', width: 360, height: 780, deviceScaleFactor: 3, category: 'Sony' },
  { name: 'Xperia 5 V', width: 360, height: 780, deviceScaleFactor: 3, category: 'Sony' },
  { name: 'Xperia 10 VI', width: 360, height: 780, deviceScaleFactor: 2, category: 'Sony' },
  { name: 'Xperia 10 V', width: 360, height: 780, deviceScaleFactor: 2, category: 'Sony' },
  // Desktop
  { name: '1280×800', width: 1280, height: 800, deviceScaleFactor: 1, category: 'Desktop' },
  { name: '1366×768', width: 1366, height: 768, deviceScaleFactor: 1, category: 'Desktop' },
  { name: '1440×900', width: 1440, height: 900, deviceScaleFactor: 1, category: 'Desktop' },
  { name: 'MacBook Pro 14"', width: 1512, height: 982, deviceScaleFactor: 2, category: 'Desktop' },
  { name: 'MacBook Pro 16"', width: 1728, height: 1117, deviceScaleFactor: 2, category: 'Desktop' },
  { name: '1920×1080', width: 1920, height: 1080, deviceScaleFactor: 1, category: 'Desktop' },
  { name: '2560×1440', width: 2560, height: 1440, deviceScaleFactor: 1, category: 'Desktop' },
  { name: 'MacBook Pro 14" native', width: 3456, height: 2234, deviceScaleFactor: 2, category: 'Desktop' },
  { name: '4K', width: 3840, height: 2160, deviceScaleFactor: 1, category: 'Desktop' },
  { name: '5K iMac', width: 5120, height: 2880, deviceScaleFactor: 2, category: 'Desktop' },
];

export const DEVICE_CATEGORIES = [...new Set(DEVICE_PRESETS.map((d) => d.category!))];
